
        <!DOCTYPE html>
        <html lang="en">
          <head>
            <meta charset="utf-8" />
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <base href="/1.7.9/">
          </head>
          <body>
            <h1>Index of 1.7.9/</h1>
            <hr>
            <pre><a href="docs/">docs/</a><br><a href="i18n/">i18n/</a><br><a href="test-bundles/">test-bundles/</a><br><a href="angular-1.7.9.zip">angular-1.7.9.zip</a><br><a href="angular-animate.js">angular-animate.js</a><br><a href="angular-animate.min.js">angular-animate.min.js</a><br><a href="angular-animate.min.js.map">angular-animate.min.js.map</a><br><a href="angular-aria.js">angular-aria.js</a><br><a href="angular-aria.min.js">angular-aria.min.js</a><br><a href="angular-aria.min.js.map">angular-aria.min.js.map</a><br><a href="angular-cookies.js">angular-cookies.js</a><br><a href="angular-cookies.min.js">angular-cookies.min.js</a><br><a href="angular-cookies.min.js.map">angular-cookies.min.js.map</a><br><a href="angular-csp.css">angular-csp.css</a><br><a href="angular-loader.js">angular-loader.js</a><br><a href="angular-loader.min.js">angular-loader.min.js</a><br><a href="angular-loader.min.js.map">angular-loader.min.js.map</a><br><a href="angular-message-format.js">angular-message-format.js</a><br><a href="angular-message-format.min.js">angular-message-format.min.js</a><br><a href="angular-message-format.min.js.map">angular-message-format.min.js.map</a><br><a href="angular-messages.js">angular-messages.js</a><br><a href="angular-messages.min.js">angular-messages.min.js</a><br><a href="angular-messages.min.js.map">angular-messages.min.js.map</a><br><a href="angular-mocks.js">angular-mocks.js</a><br><a href="angular-parse-ext.js">angular-parse-ext.js</a><br><a href="angular-parse-ext.min.js">angular-parse-ext.min.js</a><br><a href="angular-parse-ext.min.js.map">angular-parse-ext.min.js.map</a><br><a href="angular-resource.js">angular-resource.js</a><br><a href="angular-resource.min.js">angular-resource.min.js</a><br><a href="angular-resource.min.js.map">angular-resource.min.js.map</a><br><a href="angular-route.js">angular-route.js</a><br><a href="angular-route.min.js">angular-route.min.js</a><br><a href="angular-route.min.js.map">angular-route.min.js.map</a><br><a href="angular-sanitize.js">angular-sanitize.js</a><br><a href="angular-sanitize.min.js">angular-sanitize.min.js</a><br><a href="angular-sanitize.min.js.map">angular-sanitize.min.js.map</a><br><a href="angular-touch.js">angular-touch.js</a><br><a href="angular-touch.min.js">angular-touch.min.js</a><br><a href="angular-touch.min.js.map">angular-touch.min.js.map</a><br><a href="angular.js">angular.js</a><br><a href="angular.min.js">angular.min.js</a><br><a href="angular.min.js.map">angular.min.js.map</a><br><a href="errors.json">errors.json</a><br><a href="sitemap.xml">sitemap.xml</a><br><a href="version.json">version.json</a><br><a href="version.txt">version.txt</a><br></pre>
          </body>
        </html>